repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --max-warnings 0
        language: system
        types_or: [javascript, jsx, ts, tsx]
      - id: tsc
        name: tsc --noEmit
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false
